In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.optim import lr_scheduler
import numpy as np
import torchvision
from torchvision import datasets, models, transforms
import matplotlib.pyplot as plt
import time
import os
import pandas as pd
from sklearn.model_selection import train_test_split
import shutil
import time
import copy
from PIL import Image
import glob
import cv2


filepath = 'C:/Users/smit gandhi/Desktop/FACE mask temp/maskmodel3_GoogleNet.pth'
model = torch.load(filepath)


class_names = ['with_mask',
 'without_mask'
]



def process_image(image):
    ''' Scales, crops, and normalizes a PIL image for a PyTorch model,
        returns an Numpy array
    '''
    
    # TODO: Process a PIL image for use in a PyTorch model
    #pil_image = Image.open(image)
    pil_image = image
   
    image_transforms = transforms.Compose([
        transforms.Resize(256),
        transforms.CenterCrop(224),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
    ])
    
    img = image_transforms(pil_image)
    return img
    
    


def classify_face(image):
    device = torch.device("cpu")
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    #im_pil = image.fromarray(image)
    #image = np.asarray(im)
    im = Image.fromarray(image)
    image = process_image(im)
    print('image_processed')
    img = image.unsqueeze_(0)
    img = image.float()

    model.eval()
    model.cpu()
    output = model(image)
    print(output,'##############output###########')
    _, predicted = torch.max(output, 1)
    print(predicted.data[0],"predicted")


    classification1 = predicted.data[0]
    index = int(classification1)
    print(class_names[index])
    return class_names[index]


'''
if __name__ == '__main__':
    #map_location=torch.device('cpu')
    image = cv2.imread('C:/Users/smit gandhi/Desktop/Maskthe faceimages/maksssksksss6.png')
    label = classify_face(image)
    print("the label is", label)
    '''

'\nif __name__ == \'__main__\':\n    #map_location=torch.device(\'cpu\')\n    image = cv2.imread(\'C:/Users/smit gandhi/Desktop/Maskthe faceimages/maksssksksss6.png\')\n    label = classify_face(image)\n    print("the label is", label)\n    '

In [ ]:
import cv2
import os
from keras.models import load_model
import numpy as np
from pygame import mixer
import time
# from lebel import classify_face


mixer.init()
sound = mixer.Sound('C:/Users/smit gandhi/Desktop/FaceMask_detection_alarm.wav')


#face = cv2.CascadeClassifier('/media/preeth/Data/prajna_files/Drowsiness_detection/haar_cascade_files/haarcascade_frontalface_alt.xml')
cap = cv2.VideoCapture(0)
font = cv2.FONT_HERSHEY_COMPLEX_SMALL
score=0
thicc=2
#faces = face.detectMultiScale(gray,minNeighbors=5,scaleFactor=1.1,minSize=(25,25))
while(True):
    ret, frame = cap.read()
    height,width = frame.shape[:2]
    label = classify_face(frame)
    if(label == 'with_mask'):
        print("No Beep")
    else:
        sound.play()
        print("Beep")   
    cv2.putText(frame,str(label),(100,height-20), font, 1,(255,255,255),1,cv2.LINE_AA)
    cv2.imshow('frame',frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
cap.release()
cv2.destroyAllWindows()

pygame 2.0.1 (SDL 2.0.14, Python 3.8.3)
Hello from the pygame community. https://www.pygame.org/contribute.html
image_processed
tensor([[-0.8293,  0.6067]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-0.9018,  0.6162]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-0.8559,  0.5329]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-0.9509,  0.6792]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-0.8576,  0.6195]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-0.8162,  0.6223]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-0.7413,  0.5219]], gra

tensor([[-0.5742,  0.2312]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-0.4537,  0.0606]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-0.6281,  0.3068]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-0.6973,  0.3295]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-0.4237,  0.0987]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-0.6290,  0.2917]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-0.8284,  0.4474]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-0.7917,  0

tensor([[-0.2749, -0.0660]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-0.8997,  0.5730]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-0.6348,  0.3350]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-0.6774,  0.3559]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-0.8644,  0.3865]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-0.7331,  0.4218]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-0.6457,  0.5039]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-0.6907,  0

tensor([[-0.4054,  0.1465]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-0.1545, -0.1750]], grad_fn=<AddmmBackward>) ##############output###########
tensor(0) predicted
with_mask
No Beep
image_processed
tensor([[-0.3214, -0.0100]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-0.3672,  0.1654]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-0.3453,  0.1694]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-0.4664,  0.2829]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-0.3518,  0.0527]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-0.6541,  0

tensor([[-0.6179,  0.2824]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-0.5197,  0.2072]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-0.4136,  0.2386]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-0.5264,  0.1645]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-0.3453,  0.0051]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-0.4658,  0.1261]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-0.4377,  0.0440]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-0.5797,  0

tensor([[ 0.8958, -0.8753]], grad_fn=<AddmmBackward>) ##############output###########
tensor(0) predicted
with_mask
No Beep
image_processed
tensor([[ 0.5541, -0.5349]], grad_fn=<AddmmBackward>) ##############output###########
tensor(0) predicted
with_mask
No Beep
image_processed
tensor([[ 0.6873, -0.6195]], grad_fn=<AddmmBackward>) ##############output###########
tensor(0) predicted
with_mask
No Beep
image_processed
tensor([[ 0.5580, -0.5919]], grad_fn=<AddmmBackward>) ##############output###########
tensor(0) predicted
with_mask
No Beep
image_processed
tensor([[ 0.6098, -0.4472]], grad_fn=<AddmmBackward>) ##############output###########
tensor(0) predicted
with_mask
No Beep
image_processed
tensor([[ 0.9458, -0.7379]], grad_fn=<AddmmBackward>) ##############output###########
tensor(0) predicted
with_mask
No Beep
image_processed
tensor([[ 0.8528, -0.8573]], grad_fn=<AddmmBackward>) ##############output###########
tensor(0) predicted
with_mask
No Beep
image_processed
tensor([[ 0.7315, -0

tensor([[-0.4738,  0.6498]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-0.5713,  0.6928]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-1.1950,  1.1141]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-1.3424,  1.1777]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-1.1408,  0.9798]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-0.6276,  0.4897]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-0.9438,  0.7266]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-0.9655,  0

tensor([[-0.5219,  0.2713]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-0.3771,  0.1531]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-0.4644,  0.2752]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-0.7331,  0.5769]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-0.9261,  0.7581]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-0.9712,  0.6718]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-0.9516,  0.6028]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-0.4513,  0

tensor([[ 0.0939, -0.1254]], grad_fn=<AddmmBackward>) ##############output###########
tensor(0) predicted
with_mask
No Beep
image_processed
tensor([[-0.0721,  0.0622]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-0.0080, -0.0462]], grad_fn=<AddmmBackward>) ##############output###########
tensor(0) predicted
with_mask
No Beep
image_processed
tensor([[ 0.1739, -0.1599]], grad_fn=<AddmmBackward>) ##############output###########
tensor(0) predicted
with_mask
No Beep
image_processed
tensor([[ 0.1627, -0.1928]], grad_fn=<AddmmBackward>) ##############output###########
tensor(0) predicted
with_mask
No Beep
image_processed
tensor([[ 0.5521, -0.4178]], grad_fn=<AddmmBackward>) ##############output###########
tensor(0) predicted
with_mask
No Beep
image_processed
tensor([[ 0.6889, -0.5864]], grad_fn=<AddmmBackward>) ##############output###########
tensor(0) predicted
with_mask
No Beep
image_processed
tensor([[ 1.0880, -1

tensor([[ 0.2574, -0.4362]], grad_fn=<AddmmBackward>) ##############output###########
tensor(0) predicted
with_mask
No Beep
image_processed
tensor([[ 0.2877, -0.4061]], grad_fn=<AddmmBackward>) ##############output###########
tensor(0) predicted
with_mask
No Beep
image_processed
tensor([[ 0.1653, -0.2964]], grad_fn=<AddmmBackward>) ##############output###########
tensor(0) predicted
with_mask
No Beep
image_processed
tensor([[ 0.3226, -0.3927]], grad_fn=<AddmmBackward>) ##############output###########
tensor(0) predicted
with_mask
No Beep
image_processed
tensor([[ 0.2276, -0.3605]], grad_fn=<AddmmBackward>) ##############output###########
tensor(0) predicted
with_mask
No Beep
image_processed
tensor([[ 0.2397, -0.3312]], grad_fn=<AddmmBackward>) ##############output###########
tensor(0) predicted
with_mask
No Beep
image_processed
tensor([[ 0.0532, -0.2028]], grad_fn=<AddmmBackward>) ##############output###########
tensor(0) predicted
with_mask
No Beep
image_processed
tensor([[ 0.5605, -0

tensor([[ 0.1433, -0.3188]], grad_fn=<AddmmBackward>) ##############output###########
tensor(0) predicted
with_mask
No Beep
image_processed
tensor([[ 0.3626, -0.3968]], grad_fn=<AddmmBackward>) ##############output###########
tensor(0) predicted
with_mask
No Beep
image_processed
tensor([[ 0.0700, -0.1459]], grad_fn=<AddmmBackward>) ##############output###########
tensor(0) predicted
with_mask
No Beep
image_processed
tensor([[ 0.1841, -0.3434]], grad_fn=<AddmmBackward>) ##############output###########
tensor(0) predicted
with_mask
No Beep
image_processed
tensor([[ 0.1384, -0.2607]], grad_fn=<AddmmBackward>) ##############output###########
tensor(0) predicted
with_mask
No Beep
image_processed
tensor([[ 0.0956, -0.2010]], grad_fn=<AddmmBackward>) ##############output###########
tensor(0) predicted
with_mask
No Beep
image_processed
tensor([[ 0.2695, -0.4146]], grad_fn=<AddmmBackward>) ##############output###########
tensor(0) predicted
with_mask
No Beep
image_processed
tensor([[ 0.3711, -0

tensor([[ 0.3984, -0.4431]], grad_fn=<AddmmBackward>) ##############output###########
tensor(0) predicted
with_mask
No Beep
image_processed
tensor([[ 0.2911, -0.3987]], grad_fn=<AddmmBackward>) ##############output###########
tensor(0) predicted
with_mask
No Beep
image_processed
tensor([[ 0.4068, -0.5782]], grad_fn=<AddmmBackward>) ##############output###########
tensor(0) predicted
with_mask
No Beep
image_processed
tensor([[ 0.3598, -0.4353]], grad_fn=<AddmmBackward>) ##############output###########
tensor(0) predicted
with_mask
No Beep
image_processed
tensor([[ 0.3970, -0.5017]], grad_fn=<AddmmBackward>) ##############output###########
tensor(0) predicted
with_mask
No Beep
image_processed
tensor([[ 0.4497, -0.5633]], grad_fn=<AddmmBackward>) ##############output###########
tensor(0) predicted
with_mask
No Beep
image_processed
tensor([[ 0.2455, -0.3694]], grad_fn=<AddmmBackward>) ##############output###########
tensor(0) predicted
with_mask
No Beep
image_processed
tensor([[ 0.2601, -0

tensor([[ 0.4094, -0.4537]], grad_fn=<AddmmBackward>) ##############output###########
tensor(0) predicted
with_mask
No Beep
image_processed
tensor([[ 0.6310, -0.6506]], grad_fn=<AddmmBackward>) ##############output###########
tensor(0) predicted
with_mask
No Beep
image_processed
tensor([[ 0.9926, -0.9710]], grad_fn=<AddmmBackward>) ##############output###########
tensor(0) predicted
with_mask
No Beep
image_processed
tensor([[ 0.5131, -0.4851]], grad_fn=<AddmmBackward>) ##############output###########
tensor(0) predicted
with_mask
No Beep
image_processed
tensor([[ 0.6364, -0.7339]], grad_fn=<AddmmBackward>) ##############output###########
tensor(0) predicted
with_mask
No Beep
image_processed
tensor([[ 0.5063, -0.5468]], grad_fn=<AddmmBackward>) ##############output###########
tensor(0) predicted
with_mask
No Beep
image_processed
tensor([[ 0.6170, -0.5893]], grad_fn=<AddmmBackward>) ##############output###########
tensor(0) predicted
with_mask
No Beep
image_processed
tensor([[ 0.7676, -0

tensor([[-0.4340,  0.1602]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-0.1530, -0.0126]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-0.5456,  0.2827]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-0.6102,  0.3251]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-0.3560,  0.1024]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-0.5737,  0.1781]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-0.3527,  0.0443]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-0.5809,  0

tensor([[-0.7750,  0.4085]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-0.7056,  0.4139]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-0.3839,  0.2771]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-0.3255,  0.1686]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-0.5165,  0.3014]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-0.5117,  0.3434]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-0.2822,  0.0868]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-0.0455,  0

tensor([[-0.6809,  0.4311]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-0.2401,  0.0541]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-0.7121,  0.3423]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-0.2660, -0.0922]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-0.2621, -0.0229]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-0.6040,  0.2739]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-0.6343,  0.2498]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-0.5088,  0

tensor([[ 0.6460, -0.7244]], grad_fn=<AddmmBackward>) ##############output###########
tensor(0) predicted
with_mask
No Beep
image_processed
tensor([[ 0.6160, -0.7004]], grad_fn=<AddmmBackward>) ##############output###########
tensor(0) predicted
with_mask
No Beep
image_processed
tensor([[ 0.6342, -0.8006]], grad_fn=<AddmmBackward>) ##############output###########
tensor(0) predicted
with_mask
No Beep
image_processed
tensor([[ 0.9031, -1.0055]], grad_fn=<AddmmBackward>) ##############output###########
tensor(0) predicted
with_mask
No Beep
image_processed
tensor([[ 1.1584, -1.1998]], grad_fn=<AddmmBackward>) ##############output###########
tensor(0) predicted
with_mask
No Beep
image_processed
tensor([[ 0.4299, -0.5657]], grad_fn=<AddmmBackward>) ##############output###########
tensor(0) predicted
with_mask
No Beep
image_processed
tensor([[ 0.4909, -0.6255]], grad_fn=<AddmmBackward>) ##############output###########
tensor(0) predicted
with_mask
No Beep
image_processed
tensor([[ 0.4777, -0

tensor([[-0.4653,  0.0358]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-0.4386,  0.0881]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-0.4184,  0.1361]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-0.4050,  0.2391]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-0.2321, -0.0034]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-0.2427,  0.1095]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-0.2547,  0.0590]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-0.2916,  0

tensor([[-1.0466,  0.7695]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-2.0274,  1.5672]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-2.1569,  1.7291]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-1.7489,  1.4056]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-1.7862,  1.4851]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-1.5060,  1.0976]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-1.6114,  1.2483]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-1.4648,  1

tensor([[-0.9450,  0.7063]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-1.2810,  0.9238]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-0.9843,  0.6837]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-0.9261,  0.6301]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-1.1044,  0.9247]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-1.1852,  0.8873]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-1.1147,  0.8625]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-1.0848,  0

tensor([[-1.1854,  0.9575]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-1.3529,  1.0209]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-1.2016,  0.8597]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-1.2433,  1.0057]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-1.1259,  0.8780]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-0.8687,  0.6664]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-0.9808,  0.6257]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-1.1687,  0

tensor([[-2.9911,  2.5408]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-3.0744,  2.6195]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-3.3914,  2.8320]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-3.5809,  2.9622]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-3.6632,  2.9937]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-3.4814,  2.8765]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-3.2051,  2.6585]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-3.4681,  2

tensor([[-1.9390,  1.6551]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-1.9048,  1.5195]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-1.7887,  1.4566]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-1.4602,  1.1934]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-1.7234,  1.4496]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-1.5263,  1.3088]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-1.3228,  1.0761]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-1.5120,  1

tensor([[-2.2636,  1.7222]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-2.0759,  1.6285]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-2.4201,  1.8509]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-2.4993,  1.9275]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-2.5826,  2.0439]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-2.8409,  2.3894]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-2.5258,  2.0141]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-2.4092,  1

KeyboardInterrupt: 